### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by joehillen** [JadielTeofilo/i3blocks-stop-watch#2]
By default, anything without a copyright license is [All Rights Reserved](https://en.wikipedia.org/wiki/All_rights_reserved) meaning I actually violated your copyright by forking your repo. I'm guessing that wasn't your intent.

Please add a license to this repo https://choosealicense.com/

**Comment by JadielTeofilo** [comment]
Just fixed it on [v1.0.1](https://github.com/JadielTeofilo/i3blocks-stop-watch/tree/v1.0.1). Thanks for the feedback.
